GET http://localhost:8080/rota

###
GET http://localhost:8080/rota/t-5/cidades

###

DELETE http://localhost:8080/rota/t-51

###

POST http://localhost:8080/rota
Content-Type: application/json

{"idRota": "t-51", "nome": "teste2", "nomeOrigem": "Mossoro", "nomeDestino": "Natal"}

###

POST http://localhost:8080/rota/cidades
Content-Type: application/json

[
    {"idRota": "t-5", "nomeCidade": "Natal", "numSeq": "0"},
    {"idRota": "t-5", "nomeCidade": "Assu", "numSeq": "1"},
    {"idRota": "t-5", "nomeCidade": "Mossoro", "numSeq": "2"}
]

###

DELETE http://localhost:8080/rota/t-5/cidades