GET http://localhost:8080/viagem

###

POST http://localhost:8080/viagem
Content-Type: application/json

{
    "data": "2021-03-05",
    "preco": 100,
    "rota": "a-n",
    "motorista": "29306192100",
    "onibus": "HZV8911",
    "status": "confirmada",
    "empresa": "1",
    "horaSaida": "22:20"
}

###

DELETE http://localhost:8080/viagem/5

###

GET http://localhost:8080/viagem/busca?origem=Assu&destino=Natal

###
GET http://localhost:8080/rota

###

DELETE http://localhost:8080/rota/t-6

###

POST http://localhost:8080/rota
Content-Type: application/json

{"idRota": "t-6", "nome": "teste2", "nomeOrigem": "Mossoro", "nomeDestino": "Natal"}

###
GET http://localhost:8080/rota/a-n/cidades

###

POST http://localhost:8080/rota/cidades
Content-Type: application/json

{
    "rotaId": "t-5",
    "cidades": [ 
        {"nome": "Mossoro", "numSeq": "0"},
        {"nome": "Assu", "numSeq": "1"},
        {"nome": "Natal", "numSeq": "2"}
    ]
}

###

DELETE http://localhost:8080/rota/t-5/cidades

###

GET http://localhost:8080/cidades

###

POST http://localhost:8080/cidades
Content-Type: application/json

{
    "nome": "cidade nome teste"
}

###

DELETE http://localhost:8080/cidades/18

###

GET http://localhost:8080/userHomepage/